chore: check missing coverage_report.txt

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -41,6 +41,11 @@ jobs:
         run: |
           cd currency_converter
           poetry run coverage run manage.py test
+          poetry run coverage report -m > coverage_report.txt || echo "Failed to generate coverage report"
+          ls -al # List files in the current directory for debugging
+          cat coverage_report.txt || echo "Failed to read coverage report"
+          total_coverage=$(grep "^TOTAL" coverage_report.txt | awk '{print $NF}')
+          echo "Total Coverage: $total_coverage%"
 
       - name: Generate coverage report
         run: |
